<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\OpenCase.Application\OpenCase.Application.csproj" />
    <ProjectReference Include="..\OpenCase.Infrastructure\OpenCase.Infrastructure.csproj" />
    <ProjectReference Include="..\OpenCase.Shared\OpenCase.Shared.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

</Project>
